name: CI/CD

permissions:
  pages: write
  id-token: write

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist/minesweeper

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v2
